import numpy as np
from scipy.io import wavfile
from scipy.fft import fft
import pandas as pd
from PIL import Image
import sys

def process_image_to_fft_excel(image_path, audio_path, output_excel):
    # Read the image to get its dimensions
    image = Image.open(image_path)
    width, height = image.size

    # Define the desired number of rows for the Excel file
    desired_rows = 1028 

    # Read the audio file generated by img2wav
    sample_rate, data = wavfile.read(audio_path)

    # Perform FFT on the audio data
    fft_values = fft(data)

    # Determine the number of columns based on the length of the audio data
    num_samples = len(data)
    desired_columns = num_samples // desired_rows

    # Ensure we have enough FFT values to fill the desired matrix dimensions
    required_size = desired_rows * desired_columns
    if len(fft_values) > required_size:
        # Trim the FFT values if there are too many
        fft_values = fft_values[:required_size]

    # Reshape the FFT values to fit the desired matrix dimensions
    fft_matrix = np.abs(fft_values).reshape((desired_rows, desired_columns))

    # Create a DataFrame to store the FFT matrix
    df = pd.DataFrame(fft_matrix)

    # Save the DataFrame to an Excel file
    df.to_excel(output_excel, index=False)

    print(f"FFT values have been saved to {output_excel}")

if __name__ == "__main__":
    if len(sys.argv) != 4:
        print("Usage: python script.py <image_path> <audio_path> <output_excel>")
        sys.exit(1)

    image_path = sys.argv[1]
    audio_path = sys.argv[2]
    output_excel = sys.argv[3]
    process_image_to_fft_excel(image_path, audio_path, output_excel)
